# Generated by Django 4.2 on 2023-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_id',
            field=models.IntegerField(default=0),
        ),
    ]
